In [1]:
import numpy as np
"""Link to the numpy docs: https://docs.scipy.org/doc/numpy-1.13.0/reference/"""

'Link to the numpy docs: https://docs.scipy.org/doc/numpy-1.13.0/reference/'

Lets solve a few basic numpy problems

In [3]:
def get_range(start, end, step):
    """Return an array of given range with specific step"""
    return(np.arange(start,end,step))
print(get_range(3,5,1))

[3 4]


In [4]:
def new_shape(array, new_shape):
    """Return an array of given shape"""
    #check if array can be reshaped to given dimensions
    print array.shape
    olds=1
    news=1
    for i in array.shape:
        olds*=i
    for i in new_shape:
        news*=i
    
    if news!=olds:
        return (array)

    #define the function to reshape the array
    array=array.reshape(new_shape)
    
    #return the array
    return(array)

a=np.array([[3,4,5,6],[1,2,3,4]])

a=new_shape(a,[8,1])
print a

(2, 4)
[[3]
 [4]
 [5]
 [6]
 [1]
 [2]
 [3]
 [4]]


In [5]:
def reverse_array(old_array):
    """Return the reversed array"""
    return(np.flip(old_array,0))
print(reverse_array([1,2,3]))

[3 2 1]


In [6]:
def stack_lists(lists):
    """Return an array containing lists stacked horizontally"""
    return(np.hstack(lists))
print(stack_lists([[1,2,3],[1,2],[1]]))

[1 2 3 1 2 1]


In [7]:
def get_trignometric_values(angle):
    """Return an array containing sine, cosine and tangent values of the given angle stacked horizontally"""
    return (np.stack((np.sin(angle),np.cos(angle),np.tan(angle))))
print(get_trignometric_values(3.14))

[ 0.00159265 -0.99999873 -0.00159265]


In [8]:
def invert_array(array):
    """Return the pseudo inverse of the given array; read more about pseudo inverse at: 
    https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse"""
    array = np.linalg.pinv(array)
    return(array)
print( invert_array([[1, 2 ,3],[3, 2, 1],[1, 2, 2]]) )

[[ 5.00000000e-01  5.00000000e-01 -1.00000000e+00]
 [-1.25000000e+00 -2.50000000e-01  2.00000000e+00]
 [ 1.00000000e+00 -1.66222462e-16 -1.00000000e+00]]


In [9]:
def flatten_array(array):
    """Return the flattened array"""
    return(np.ndarray.flatten(array))
a=[[1,2],[3,4]]
print(flatten_array(np.array(a)))

[1 2 3 4]


In [12]:
def add_noise(array, mean, std):
    """Add gaussian noise with given mean and standard deviation; read more about the normal distribution at:
    https://en.wikipedia.org/wiki/Normal_distribution"""
    return(np.random.normal(mean, std, array.size))
# a=np.array([1,2,3,4,5,6,7,8])
a=np.array([0, 0, 0, 0])
print (np.std(a))
anew=add_noise(a,1,1)
print (anew)
print(np.std(anew))
print(np.std(a+anew))
print(np.mean(anew))

0.0
[1.54287456 2.47849598 3.04795726 1.05650294]
0.7781974106169678
0.7781974106169678
2.0314576839724157


In [13]:
def expand_array(array, axis):
    """Return an array expanded along the column"""
    a = np.expand_dims(array,axis)
    return(a)
expand_array([[1,2,3],[1,2,3]],0)
# expand_array([1,2,3],1)

array([[[1, 2, 3],
        [1, 2, 3]]])

In [24]:
import math
def sigmoid_fn(array):
    """Return an array with the sigmoid values"""
    return(1/(1+np.exp(-1*(array))))
sigmoid_fn(np.array([0,1,2,3]))

array([0.5       , 0.73105858, 0.88079708, 0.95257413])

In [25]:
import scipy.stats
def get_means(array):
    """Return arithmetic mean, geometric mean, harmonic mean and log means in a column array"""
    #define function for arithmetic mean
    a = np.mean(array)
    #define function for geometric mean
    b = scipy.stats.gmean(array)
    #define function for harmonic mean
    c = (scipy.stats.hmean(array))
    #define function for log means
    d = (np.log(array).mean())
    
    return(np.hstack([a,b,c,d]))
arr = np.arange(1,10,2)
get_means(arr)

array([5.        , 3.93628343, 2.79751332, 1.37023699])

In [24]:
def return_count(array, threshold):
    """Return the number of elements above the threshold in an array"""
    return((np.where(array > threshold))[0].shape[0])
print(return_count(np.array([1,2,3]),1))
print(return_count(np.array([1,2,3]),2))

2
1


In [35]:
def column_sum(array, column_no):
    """Return the sum of all the elements in a column of the array"""
    #check if column exists in array, else return(np.nan)
    if column_no>=array.shape[1]:
        return np.nan
    return (np.sum(array, axis=0))[column_no]
column_sum(np.array([[1,2],[2,3],[3,4]]),0)

6

In [33]:
def row_sum(array, row_no):
    """Return the sum of all the elements in a row of the array"""
    #check if row exists in array, else return(np.nan)
    if row_no>=array.shape[0]:
        return np.nan
    #define function to return the sum of elements in the given row
    
    #return the value
    return(np.sum(array[row_no]))

print(row_sum(np.array([[1,3],[2,1]]),1))
print(row_sum(np.array([[1,3],[2,1]]),3))

3
nan


In [15]:
def check_diag(array):
    """Return True if the matrix is diagonal"""
    return((np.count_nonzero(array - np.diag(np.diag(array))))==0)
print(check_diag(np.array([[1,0],[0,1]])))
print(check_diag(np.array([[1,1],[0,1]])))

True
False
